# Generated by Django 6.0 on 2026-01-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kycdocument",
            name="document_url",
            field=models.CharField(max_length=500),
        ),
    ]
