# Generated by Django 5.2.16 on 2026-08-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_kycdocument_reviewed_by_locker_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='payment_grace_until',
            field=models.DateTimeField(blank=True, help_text='Set when a paid-plan renewal fails; non-null and not yet expired means the account is in its 7-day grace period.', null=True),
        ),
        migrations.AddField(
            model_name='locker',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=10),
        ),
    ]
