# Generated by Django 5.2.16 on 2026-08-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_locker_payment_grace_until_locker_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='premium_expires_at',
            field=models.DateField(blank=True, help_text='Date the current Premium subscription term ends. Null for Free-plan lockers.', null=True),
        ),
    ]
