# Generated by Django 5.2.16 on 2026-08-25 11:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_locker_premium_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='premium_savings_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Denormalized running total (spec 11a) — real Premium discount already applied if this locker is Premium, or the hypothetical if it's Free. Incremented at the exact moment a quotation/shipment/batch charge is finalized as paid (see record_premium_savings()); never recomputed live via aggregate queries on page load.", max_digits=10),
        ),
    ]
