# Generated by Django 5.2.16 on 2026-08-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_backfill_premium_savings_amount'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='locker',
            index=models.Index(fields=['plan_type', 'premium_expires_at'], name='idx_locker_plan_premium_exp'),
        ),
    ]
