# Generated by Django 5.2.16 on 2026-08-27 05:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_locker_idx_locker_plan_premium_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, help_text='Set once account_deletion.delete_user_account() has anonymized this row. The row itself is never hard-deleted — see apps/accounts/account_deletion.py for why (Payment/Shipment/BatchCharge financial records must be retained and CASCADE from User).', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, help_text='Set when the user submits a self-service account deletion request (DPDP Act erasure request).', null=True),
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_type', models.CharField(choices=[('signup', 'Account Signup'), ('kyc_upload', 'KYC Document Upload')], max_length=20)),
                ('policy_version', models.CharField(help_text='Snapshot of AppSettings.privacy_policy_version at the moment consent was given.', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('consented_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consent Record',
                'verbose_name_plural': 'Consent Records',
                'ordering': ['-consented_at'],
            },
        ),
    ]
