# Generated by Django 6.0 on 2026-01-03 10:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parcel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tracking_number", models.CharField(max_length=100)),
                ("carrier", models.CharField(blank=True, max_length=100)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("inspection_notes", models.TextField(blank=True)),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("dimensions", models.CharField(blank=True, max_length=100)),
                ("item_name", models.CharField(blank=True, max_length=255)),
                (
                    "item_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("item_currency", models.CharField(default="INR", max_length=3)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("clothing", "Clothing & Accessories"),
                            ("electronics", "Electronics"),
                            ("cosmetics", "Cosmetics & Personal Care"),
                            ("food", "Food & Supplements"),
                            ("home", "Home & Kitchen"),
                            ("books", "Books & Stationery"),
                            ("jewelry", "Jewelry & Watches"),
                            ("sports", "Sports & Fitness"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("customs_description", models.TextField(blank=True)),
                ("invoice_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Inspection"),
                            ("action_required", "Action Required"),
                            ("approved", "Approved - Ready to Ship"),
                            ("shipped", "Shipped"),
                            ("return_requested", "Return Requested"),
                            ("return_approved", "Return Approved"),
                            ("returned", "Returned"),
                            ("discard_requested", "Discard Requested"),
                            ("discarded", "Discarded"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcels",
                        to="accounts.locker",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parcel",
                "verbose_name_plural": "Parcels",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="DiscardRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("confirmed", "Confirmed"),
                            ("discarded", "Discarded"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("discarded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parcel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discard_requests",
                        to="locker.parcel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discard Request",
                "verbose_name_plural": "Discard Requests",
            },
        ),
        migrations.CreateModel(
            name="ParcelImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image_url", models.URLField()),
                ("is_primary", models.BooleanField(default=False)),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parcel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="locker.parcel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parcel Image",
                "verbose_name_plural": "Parcel Images",
                "ordering": ["-is_primary", "-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                (
                    "return_tracking_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("return_carrier", models.CharField(blank=True, max_length=100)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
                (
                    "parcel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_requests",
                        to="locker.parcel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Return Request",
                "verbose_name_plural": "Return Requests",
                "ordering": ["-requested_at"],
            },
        ),
    ]
