# Generated by Django 6.0 on 2026-01-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcel",
            name="tracking_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
