# Generated by Django 6.0 on 2026-01-05 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locker", "0002_remove_tracking_required"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parcel",
            name="dimensions",
        ),
    ]
