# Generated by Django 6.0 on 2026-01-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locker", "0003_remove_parcel_dimensions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parcelimage",
            name="image_url",
        ),
        migrations.AddField(
            model_name="parcelimage",
            name="image_path",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
