# Generated by Django 5.2.10 on 2026-01-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locker", "0004_update_parcelimage_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="discardrequest",
            name="display_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=60,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="display_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="parcelimage",
            name="display_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=60,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="display_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=60,
                null=True,
                unique=True,
            ),
        ),
    ]
