# Generated by Django 5.2.10 on 2026-02-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_kycdocument_reviewed_by_locker_is_active_and_more"),
        ("locker", "0005_discardrequest_display_id_parcel_display_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discardrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="height_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Height in cm",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="length_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Length in cm",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="width_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Width in cm",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="discardrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("confirmed", "Confirmed"),
                    ("discarded", "Discarded"),
                ],
                db_index=True,
                default="requested",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="invoice_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Inspection"),
                    ("action_required", "Action Required"),
                    ("approved", "Approved - Ready to Ship"),
                    ("shipped", "Shipped"),
                    ("return_requested", "Return Requested"),
                    ("return_approved", "Return Approved"),
                    ("returned", "Returned"),
                    ("discard_requested", "Discard Requested"),
                    ("discarded", "Discarded"),
                ],
                db_index=True,
                default="pending",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("approved", "Approved"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="requested",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="parcel",
            index=models.Index(
                fields=["locker", "status"], name="idx_parcel_locker_status"
            ),
        ),
        migrations.AddIndex(
            model_name="parcel",
            index=models.Index(
                fields=["status", "received_at"], name="idx_parcel_status_received"
            ),
        ),
    ]
