# Generated by Django 5.2.16 on 2026-08-12 10:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_locker_payment_grace_until_locker_plan_type'),
        ('locker', '0006_discardrequest_updated_at_parcel_height_cm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuota',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='quota', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('annual_quota', models.PositiveIntegerField(default=3)),
                ('passes_used', models.PositiveIntegerField(default=0)),
                ('passes_remaining', models.PositiveIntegerField(default=3)),
                ('quota_year', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Quota',
                'verbose_name_plural': 'User Quotas',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_type_at_creation', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], max_length=10)),
                ('quota_year', models.PositiveIntegerField(help_text='Calendar year of first_parcel_received_date')),
                ('batch_status', models.CharField(choices=[('active_free', 'Active - Free'), ('active_chargeable', 'Active - Chargeable'), ('closed', 'Closed'), ('pending', 'Pending (Grace Period)')], db_index=True, default='active_free', max_length=20)),
                ('first_parcel_received_date', models.DateField()),
                ('free_storage_end_date', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateField(blank=True, null=True)),
                ('current_parcel_count', models.PositiveIntegerField(default=0)),
                ('first_unpaid_charge_date', models.DateField(blank=True, null=True)),
                ('refund_issued', models.BooleanField(default=False, help_text='24-hour cancellation pass refund already applied — guards double-refund')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='accounts.locker')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['-first_parcel_received_date'],
                'indexes': [models.Index(fields=['locker', 'batch_status'], name='idx_batch_locker_status')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('batch_status__in', ['active_free', 'active_chargeable', 'pending'])), fields=('locker',), name='unique_open_batch_per_locker')],
            },
        ),
    ]
