# Generated by Django 6.0 on 2026-01-06 06:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(help_text="HTML content allowed")),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("warning", "Warning (Triangle)"),
                            ("info", "Info (Circle)"),
                            ("check", "Checkmark"),
                            ("ban", "Ban/Prohibited"),
                            ("shipping", "Shipping"),
                            ("document", "Document"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("red", "Red (Danger)"),
                            ("yellow", "Yellow (Warning)"),
                            ("blue", "Blue (Info)"),
                            ("green", "Green (Success)"),
                            ("gray", "Gray (Neutral)"),
                        ],
                        default="blue",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="content.staticpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page Section",
                "verbose_name_plural": "Page Sections",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
