# Generated by Django 5.2.10 on 2026-01-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_pagesection"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="link_text",
            field=models.CharField(
                blank=True,
                help_text="Text for link button (e.g., 'Read More')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="link_url",
            field=models.URLField(
                blank=True,
                help_text="Optional link URL for call-to-action",
                max_length=500,
                null=True,
            ),
        ),
    ]
