# Generated by Django 5.2.10 on 2026-01-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_announcement_link_text_announcement_link_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="text_bold",
            field=models.CharField(
                choices=[("bold", "Bold"), ("normal", "Normal")],
                default="normal",
                help_text="Text bold for the announcement content",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="text_size",
            field=models.CharField(
                choices=[("small", "Small"), ("normal", "Normal"), ("large", "Large")],
                default="normal",
                help_text="Text size for the announcement content",
                max_length=20,
            ),
        ),
    ]
