# Generated by Django 5.2.10 on 2026-01-13 10:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_announcement_text_bold_announcement_text_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingZone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Zone A - Americas", max_length=100
                    ),
                ),
                (
                    "countries",
                    models.TextField(
                        help_text="Comma-separated country codes, e.g., US,CA,MX"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Shipping Zone",
                "verbose_name_plural": "Shipping Zones",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ShippingRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "min_weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum weight in KG (inclusive)",
                        max_digits=6,
                    ),
                ),
                (
                    "max_weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum weight in KG (exclusive)",
                        max_digits=6,
                    ),
                ),
                (
                    "rate_type",
                    models.CharField(
                        choices=[("fixed", "Fixed Price"), ("per_kg", "Per KG Rate")],
                        default="fixed",
                        max_length=10,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Fixed price OR per-kg rate",
                        max_digits=10,
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "delivery_days_min",
                    models.PositiveIntegerField(
                        default=5, help_text="Minimum delivery days"
                    ),
                ),
                (
                    "delivery_days_max",
                    models.PositiveIntegerField(
                        default=10, help_text="Maximum delivery days"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="content.shippingzone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping Rate",
                "verbose_name_plural": "Shipping Rates",
                "ordering": ["zone", "min_weight"],
            },
        ),
    ]
