# Generated by Django 5.2.10 on 2026-02-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_shippingzone_shippingrate"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecharge",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
