# Generated by Django 5.2.16 on 2026-08-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_servicecharge_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingrate',
            options={'ordering': ['zone', 'service_type', 'min_weight'], 'verbose_name': 'Shipping Rate', 'verbose_name_plural': 'Shipping Rates'},
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='service_type',
            field=models.CharField(choices=[('express', 'Express'), ('standard', 'Standard'), ('economy', 'Economy')], db_index=True, default='standard', max_length=20),
        ),
    ]
