# Generated by Django 5.2.16 on 2026-08-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_shippingrate_options_shippingrate_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingrate',
            name='max_weight',
            field=models.DecimalField(decimal_places=2, help_text='Maximum weight in KG (inclusive)', max_digits=6),
        ),
    ]
