# Generated by Django 5.2.16 on 2026-08-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_shippingrate_max_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecharge',
            name='charge_type',
            field=models.CharField(choices=[('flat', 'Flat'), ('percentage', 'Percentage of Value')], default='flat', max_length=10),
        ),
        migrations.AddField(
            model_name='servicecharge',
            name='code',
            field=models.SlugField(blank=True, help_text="Stable key other code looks this charge up by (e.g. 'trunkassist_product_link', 'consolidation_fee'). Leave blank for a purely informational row nothing reads programmatically.", max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='servicecharge',
            name='percentage_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='e.g. 5.00 for 5%. Only used when Charge Type is Percentage.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='servicecharge',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='The flat fee (Charge Type = Flat) or the minimum floor amount (Charge Type = Percentage).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='max_weight',
            field=models.DecimalField(decimal_places=2, help_text='Maximum weight in KG (exclusive)', max_digits=6),
        ),
    ]
