# Generated by Django 5.2.10 on 2026-03-03 07:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locker", "0006_discardrequest_updated_at_parcel_height_cm_and_more"),
        ("shipments", "0004_shipment_cancelled_at_shipment_cancelled_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "display_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=60,
                        null=True,
                        unique=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("razorpay", "Razorpay"),
                            ("bank_transfer", "Bank Transfer"),
                            ("upi", "UPI"),
                            ("cash", "Cash"),
                            ("manual", "Manual / Offline"),
                        ],
                        default="razorpay",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("authorized", "Authorized"),
                            ("captured", "Captured / Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "razorpay_order_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Razorpay Order ID (order_xxxxx)",
                        max_length=100,
                    ),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Razorpay Payment ID (pay_xxxxx)",
                        max_length=100,
                    ),
                ),
                (
                    "razorpay_signature",
                    models.CharField(
                        blank=True,
                        help_text="Razorpay payment signature for verification",
                        max_length=500,
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount refunded (if any)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "refund_id",
                    models.CharField(
                        blank=True,
                        help_text="Razorpay Refund ID (rfnd_xxxxx)",
                        max_length=100,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "shipment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Shipment this payment is for (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="shipments.shipment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StorageFee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fee_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "days_overdue",
                    models.PositiveIntegerField(
                        help_text="Number of days beyond free storage period"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("waived", "Waived"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("waived_reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parcel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_fees",
                        to="locker.parcel",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Payment that covered this fee",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="storage_fees",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Storage Fee",
                "verbose_name_plural": "Storage Fees",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["user", "status"], name="idx_payment_user_status"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "created_at"], name="idx_payment_status_date"
            ),
        ),
    ]
