# Generated by Django 5.2.16 on 2026-08-07 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_invoice'),
        ('personal_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='personal_shop_request',
            field=models.ForeignKey(blank=True, help_text='TrunkAssist request this payment is for (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='personal_shop.personalshoprequest'),
        ),
    ]
