# Generated by Django 5.2.16 on 2026-08-12 10:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0008_backfill_batches_for_existing_parcels'),
        ('payments', '0003_payment_personal_shop_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('shipment', 'Shipment'), ('storage_batch', 'Storage Batch')], default='shipment', max_length=20),
        ),
        migrations.CreateModel(
            name='BatchCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('charge_date', models.DateField()),
                ('parcel_count_snapshot', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('waived', 'Waived')], default='pending', max_length=10)),
                ('waived_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='locker.batch')),
                ('payment', models.ForeignKey(blank=True, help_text='Payment that covered this charge', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_charges', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Batch Charge',
                'verbose_name_plural': 'Batch Charges',
                'ordering': ['-charge_date'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'charge_date'), name='unique_batch_charge_per_day')],
            },
        ),
    ]
