# Generated by Django 5.2.16 on 2026-08-12 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_payment_type_batchcharge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StorageFee',
        ),
    ]
