# Generated by Django 5.2.16 on 2026-08-21 06:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_delete_storagefee'),
        ('personal_shop', '0003_research_fee_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalShopInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('invoice_date', models.DateTimeField()),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('domestic_shipping_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('research_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('travel_expense_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_gateway_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf_document_url', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='personal_shop.personalshopquotation')),
            ],
            options={
                'verbose_name': 'TrunkAssist Invoice',
                'verbose_name_plural': 'TrunkAssist Invoices',
                'ordering': ['-invoice_date'],
            },
        ),
    ]
