# Generated by Django 5.2.16 on 2026-08-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_personalshopinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchcharge',
            name='amount_standard',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
