# Generated by Django 5.2.16 on 2026-08-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_batchcharge_amount_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('shipment', 'Shipment'), ('storage_batch', 'Storage Batch'), ('premium_subscription', 'Premium Subscription')], default='shipment', max_length=20),
        ),
    ]
