# Generated by Django 5.2.16 on 2026-08-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0008_backfill_batches_for_existing_parcels'),
        ('payments', '0008_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='batchcharge',
            index=models.Index(fields=['batch', 'status'], name='idx_batchcharge_batch_status'),
        ),
    ]
