# Generated by Django 5.2.17 on 2026-08-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_batchcharge_idx_batchcharge_batch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('shipment', 'Shipment'), ('storage_batch', 'Storage Batch'), ('premium_subscription', 'Premium Subscription'), ('return_service_charge', 'Return Service Charge')], default='shipment', max_length=25),
        ),
    ]
