# Generated by Django 5.2.17 on 2026-08-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='addons_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
