# Generated by Django 6.0 on 2026-01-03 10:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locker", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "shipment_type",
                    models.CharField(
                        choices=[
                            ("international", "International"),
                            ("domestic", "Domestic (India)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_payment", "Pending Payment"),
                            ("packing", "Packing"),
                            ("dispatched", "Dispatched"),
                            ("in_transit", "In Transit"),
                            ("customs", "At Customs"),
                            ("out_for_delivery", "Out for Delivery"),
                            ("delivered", "Delivered"),
                            ("returned", "Returned to Sender"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                (
                    "carrier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dhl", "DHL Express"),
                            ("fedex", "FedEx"),
                            ("ups", "UPS"),
                            ("bluedart", "BlueDart"),
                            ("dtdc", "DTDC"),
                            ("delhivery", "Delhivery"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("tracking_number", models.CharField(blank=True, max_length=100)),
                ("tracking_url", models.URLField(blank=True)),
                ("recipient_name", models.CharField(max_length=255)),
                ("recipient_phone", models.CharField(max_length=20)),
                ("recipient_email", models.EmailField(blank=True, max_length=254)),
                ("address_line1", models.CharField(max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(default="India", max_length=100)),
                (
                    "total_weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipment",
                "verbose_name_plural": "Shipments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Commercial Invoice"),
                            ("customs", "Customs Declaration"),
                            ("packing", "Packing List"),
                            ("label", "Shipping Label"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("document_url", models.URLField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="shipments.shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipment Document",
                "verbose_name_plural": "Shipment Documents",
            },
        ),
        migrations.CreateModel(
            name="ShipmentItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parcel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment_items",
                        to="locker.parcel",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shipments.shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipment Item",
                "verbose_name_plural": "Shipment Items",
                "unique_together": {("shipment", "parcel")},
            },
        ),
    ]
