# Generated by Django 6.0 on 2026-01-06 06:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeclarationPendingShipment",
            fields=[],
            options={
                "verbose_name": "Declaration Approval",
                "verbose_name_plural": "📄 Declaration Approvals",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shipments.shipment",),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("declaration_pending", "Declaration Approval Pending"),
                    ("pending_payment", "Pending Payment"),
                    ("packing", "Packing"),
                    ("dispatched", "Dispatched"),
                    ("in_transit", "In Transit"),
                    ("customs", "At Customs"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("delivered", "Delivered"),
                    ("returned", "Returned to Sender"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="TrackingEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("event_timestamp", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_events",
                        to="shipments.shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tracking Event",
                "verbose_name_plural": "Tracking Events",
                "ordering": ["-event_timestamp", "-created_at"],
            },
        ),
    ]
