# Generated by Django 5.2.10 on 2026-01-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0002_add_tracking_event_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="display_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="shipmentdocument",
            name="display_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=60,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="shipmentdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("invoice", "Commercial Invoice"),
                    ("customs", "Customer Declaration"),
                    ("packing", "Packing List"),
                    ("label", "Shipping Label"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="shipmentdocument",
            name="document_url",
            field=models.CharField(max_length=500),
        ),
    ]
