# Generated by Django 5.2.10 on 2026-02-16 06:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0003_shipment_display_id_shipmentdocument_display_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="cancelled_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="shipment",
            name="estimated_delivery_date",
            field=models.DateField(
                blank=True,
                help_text="Estimated delivery date shown to customer",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("partial", "Partially Paid"),
                    ("paid", "Paid"),
                    ("refunded", "Refunded"),
                ],
                db_index=True,
                default="unpaid",
                help_text="Payment status for this shipment",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="carrier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dhl", "DHL Express"),
                    ("fedex", "FedEx"),
                    ("ups", "UPS"),
                    ("aramex", "Aramex"),
                    ("bluedart", "BlueDart"),
                    ("dtdc", "DTDC"),
                    ("delhivery", "Delhivery"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("declaration_pending", "Declaration Approval Pending"),
                    ("pending_payment", "Pending Payment"),
                    ("packing", "Packing"),
                    ("dispatched", "Dispatched"),
                    ("in_transit", "In Transit"),
                    ("customs", "At Customs"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("delivered", "Delivered"),
                    ("returned", "Returned to Sender"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="draft",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="tracking_number",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["user", "status"], name="idx_shipment_user_status"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["status", "created_at"], name="idx_shipment_status_date"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["carrier", "tracking_number"], name="idx_shipment_carrier_track"
            ),
        ),
        migrations.AddIndex(
            model_name="trackingevent",
            index=models.Index(
                fields=["shipment", "event_timestamp"],
                name="idx_tracking_shipment_time",
            ),
        ),
    ]
