# Generated by Django 5.2.16 on 2026-08-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_shipment_cancelled_at_shipment_cancelled_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='service_type',
            field=models.CharField(blank=True, choices=[('express', 'Express'), ('standard', 'Standard'), ('economy', 'Economy')], max_length=20),
        ),
    ]
