# Generated by Django 5.2.16 on 2026-08-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_shipment_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='consolidation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Locked in at creation when 2+ parcels are combined into this shipment.', max_digits=10, null=True),
        ),
    ]
