# Generated by Django 5.2.16 on 2026-08-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_shipment_consolidation_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='consolidation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Locked in at shipment creation, regardless of parcel count.', max_digits=10, null=True),
        ),
    ]
