# Generated by Django 5.2.16 on 2026-08-24 05:52

from django.db import migrations, models


def backfill_standard_amounts(apps, schema_editor):
    """Pre-existing shipments have no *_standard figure recorded — backfill it
    from the already-charged amount so shipping_discount_amount/
    consolidation_fee_discount_amount read as 0 (no discount) for them,
    rather than showing a bogus discount against a NULL/0 standard."""
    Shipment = apps.get_model('shipments', 'Shipment')
    Shipment.objects.filter(shipping_cost__isnull=False).update(
        shipping_cost_standard=models.F('shipping_cost')
    )
    Shipment.objects.filter(consolidation_fee__isnull=False).update(
        consolidation_fee_standard=models.F('consolidation_fee')
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0007_alter_shipment_consolidation_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='consolidation_fee_standard',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Undiscounted consolidation fee before any Premium waiver — kept for display/comparison.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_cost_standard',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Undiscounted shipping rate before any Premium discount — kept for display/comparison.', max_digits=10, null=True),
        ),
        migrations.RunPython(backfill_standard_amounts, noop_reverse),
    ]
