# Generated by Django 5.2.17 on 2026-08-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0008_shipment_consolidation_fee_standard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='declaration_purpose',
            field=models.CharField(blank=True, choices=[('gift', 'Gift'), ('sale', 'Sale'), ('sample', 'Commercial Sample'), ('return', 'Return'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='shipment',
            name='declaration_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='declaration_signed_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='declaration_signed_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shipment',
            name='declaration_version',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
