# Generated by Django 5.2.17 on 2026-08-31 11:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0009_shipment_declaration_purpose_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentAddon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('insurance', 'Insurance'), ('extra_photos', 'Extra Photos'), ('priority_packing', 'Priority Packing'), ('gift_wrapping', 'Gift Wrapping')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='shipments.shipment')),
            ],
            options={
                'verbose_name': 'Shipment Add-on',
                'verbose_name_plural': 'Shipment Add-ons',
                'unique_together': {('shipment', 'code')},
            },
        ),
    ]
