# Generated by Django 5.2.10 on 2026-01-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "whatsapp_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable/disable WhatsApp notifications globally",
                    ),
                ),
                (
                    "whatsapp_api_token",
                    models.CharField(
                        blank=True,
                        help_text="Permanent Access Token from Meta App Dashboard",
                        max_length=500,
                    ),
                ),
                (
                    "whatsapp_phone_number_id",
                    models.CharField(
                        blank=True,
                        help_text="Phone Number ID from WhatsApp Business settings",
                        max_length=100,
                    ),
                ),
                (
                    "whatsapp_business_account_id",
                    models.CharField(
                        blank=True,
                        help_text="WhatsApp Business Account ID (optional)",
                        max_length=100,
                    ),
                ),
                (
                    "template_parcel_added",
                    models.CharField(
                        default="parcel_added",
                        help_text="Template name for 'Parcel Added' notification",
                        max_length=100,
                    ),
                ),
                (
                    "template_parcel_action_required",
                    models.CharField(
                        default="parcel_action_required",
                        help_text="Template name for 'Action Required' notification",
                        max_length=100,
                    ),
                ),
                (
                    "template_shipment_created",
                    models.CharField(
                        default="shipment_created",
                        help_text="Template name for 'Shipment Created' notification",
                        max_length=100,
                    ),
                ),
                (
                    "template_shipment_updated",
                    models.CharField(
                        default="shipment_updated",
                        help_text="Template name for 'Shipment Updated' notification",
                        max_length=100,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification Settings",
                "verbose_name_plural": "Notification Settings",
            },
        ),
    ]
