# Generated by Django 5.2.10 on 2026-01-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="Ruffleberry",
                        help_text="Your company/site name",
                        max_length=100,
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        default="support@ruffleberry.com",
                        help_text="Support email address",
                        max_length=254,
                    ),
                ),
                (
                    "support_phone",
                    models.CharField(
                        default="+91 7337257774",
                        help_text="Support phone number (WhatsApp enabled)",
                        max_length=20,
                    ),
                ),
                (
                    "warehouse_address",
                    models.TextField(
                        default="", help_text="Full warehouse address shown to users"
                    ),
                ),
                (
                    "whatsapp_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable/disable WhatsApp notifications"
                    ),
                ),
                (
                    "whatsapp_api_token",
                    models.CharField(
                        blank=True,
                        help_text="Permanent Access Token from Meta App Dashboard",
                        max_length=500,
                    ),
                ),
                (
                    "whatsapp_phone_number_id",
                    models.CharField(
                        blank=True,
                        help_text="Phone Number ID from WhatsApp Business",
                        max_length=100,
                    ),
                ),
                (
                    "whatsapp_business_account_id",
                    models.CharField(
                        blank=True,
                        help_text="WhatsApp Business Account ID (optional)",
                        max_length=100,
                    ),
                ),
                (
                    "template_parcel_added",
                    models.CharField(default="parcel_added", max_length=100),
                ),
                (
                    "template_parcel_action_required",
                    models.CharField(default="parcel_action_required", max_length=100),
                ),
                (
                    "template_shipment_created",
                    models.CharField(default="shipment_created", max_length=100),
                ),
                (
                    "template_shipment_updated",
                    models.CharField(default="shipment_updated", max_length=100),
                ),
                (
                    "dhl_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable DHL Express shipping"
                    ),
                ),
                (
                    "dhl_api_key",
                    models.CharField(
                        blank=True, help_text="DHL API Key", max_length=200
                    ),
                ),
                (
                    "dhl_api_secret",
                    models.CharField(
                        blank=True, help_text="DHL API Secret", max_length=200
                    ),
                ),
                (
                    "dhl_account_number",
                    models.CharField(
                        blank=True, help_text="DHL Account Number", max_length=50
                    ),
                ),
                (
                    "dhl_test_mode",
                    models.BooleanField(
                        default=True, help_text="Use DHL sandbox/test environment"
                    ),
                ),
                (
                    "fedex_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable FedEx shipping"
                    ),
                ),
                (
                    "fedex_api_key",
                    models.CharField(
                        blank=True, help_text="FedEx API Key", max_length=200
                    ),
                ),
                (
                    "fedex_secret_key",
                    models.CharField(
                        blank=True, help_text="FedEx Secret Key", max_length=200
                    ),
                ),
                (
                    "fedex_account_number",
                    models.CharField(
                        blank=True, help_text="FedEx Account Number", max_length=50
                    ),
                ),
                (
                    "fedex_test_mode",
                    models.BooleanField(
                        default=True, help_text="Use FedEx sandbox/test environment"
                    ),
                ),
                (
                    "aramex_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable Aramex shipping"
                    ),
                ),
                (
                    "aramex_username",
                    models.CharField(
                        blank=True, help_text="Aramex Username", max_length=100
                    ),
                ),
                (
                    "aramex_password",
                    models.CharField(
                        blank=True, help_text="Aramex Password", max_length=200
                    ),
                ),
                (
                    "aramex_account_number",
                    models.CharField(
                        blank=True, help_text="Aramex Account Number", max_length=50
                    ),
                ),
                (
                    "aramex_account_pin",
                    models.CharField(
                        blank=True, help_text="Aramex Account PIN", max_length=50
                    ),
                ),
                (
                    "aramex_account_entity",
                    models.CharField(
                        default="HYD",
                        help_text="Aramex Account Entity (e.g., HYD)",
                        max_length=10,
                    ),
                ),
                (
                    "aramex_test_mode",
                    models.BooleanField(
                        default=True, help_text="Use Aramex sandbox/test environment"
                    ),
                ),
                (
                    "razorpay_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable Razorpay payments"
                    ),
                ),
                (
                    "razorpay_key_id",
                    models.CharField(
                        blank=True, help_text="Razorpay Key ID", max_length=100
                    ),
                ),
                (
                    "razorpay_key_secret",
                    models.CharField(
                        blank=True, help_text="Razorpay Key Secret", max_length=200
                    ),
                ),
                (
                    "razorpay_test_mode",
                    models.BooleanField(
                        default=True, help_text="Use Razorpay test mode"
                    ),
                ),
                (
                    "supabase_url",
                    models.CharField(
                        blank=True, help_text="Supabase Project URL", max_length=200
                    ),
                ),
                (
                    "supabase_anon_key",
                    models.CharField(
                        blank=True, help_text="Supabase Anon/Public Key", max_length=500
                    ),
                ),
                (
                    "supabase_service_role_key",
                    models.CharField(
                        blank=True,
                        help_text="Supabase Service Role Key (for server-side operations)",
                        max_length=500,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "App Settings",
                "verbose_name_plural": "App Settings",
            },
        ),
        migrations.AlterModelOptions(
            name="notificationsettings",
            options={
                "managed": False,
                "verbose_name": "Notification Settings (Deprecated)",
            },
        ),
    ]
