# Generated by Django 5.2.10 on 2026-01-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_add_app_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="bluedart_api_token",
            field=models.CharField(
                blank=True, help_text="BlueDart API Token/License Key", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="bluedart_area_code",
            field=models.CharField(
                default="HYD",
                help_text="Origin Area Code (e.g., HYD, DEL, BOM)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="bluedart_customer_code",
            field=models.CharField(
                blank=True, help_text="BlueDart Customer Code", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="bluedart_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable BlueDart shipping"
            ),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="bluedart_license_key",
            field=models.CharField(
                blank=True,
                help_text="BlueDart License Key (for SOAP API)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="bluedart_login_id",
            field=models.CharField(
                blank=True, help_text="BlueDart Login ID", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="bluedart_test_mode",
            field=models.BooleanField(
                default=True, help_text="Use BlueDart sandbox/test environment"
            ),
        ),
    ]
