# Generated by Django 5.2.10 on 2026-03-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_add_bluedart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appsettings",
            name="support_phone",
            field=models.CharField(
                default="+91 123456789",
                help_text="Support phone number (WhatsApp enabled)",
                max_length=20,
            ),
        ),
    ]
