# Generated by Django 5.2.10 on 2026-03-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_alter_appsettings_support_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="razorpay_webhook_secret",
            field=models.CharField(
                max_length=200,
                blank=True,
                help_text="Razorpay Webhook Secret",
            ),
        ),
    ]
