# Generated by Django 5.2.10 on 2026-07-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_add_razorpay_webhook_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='site_name',
            field=models.CharField(default='INDIBOX', help_text='Your company/site name', max_length=100),
        ),
    ]
