# Generated by Django 5.2.16 on 2026-08-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_appsettings_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='company_gstin',
            field=models.CharField(blank=True, help_text="Your company's GSTIN (e.g., 36AAAAA0000A1Z5)", max_length=20),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='company_legal_name',
            field=models.CharField(blank=True, help_text='Registered legal business name shown on GST invoices', max_length=255),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='company_pan',
            field=models.CharField(blank=True, help_text="Your company's PAN", max_length=10),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='company_registered_address',
            field=models.TextField(blank=True, help_text='Registered business address shown on GST invoices'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='company_state',
            field=models.CharField(blank=True, help_text="Your company's registered state (e.g., Telangana) — compared against the shipment's delivery state to decide CGST+SGST vs IGST", max_length=100),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='gst_rate_percent',
            field=models.DecimalField(decimal_places=2, default=18.0, help_text='GST rate applied to domestic shipment invoices (e.g., 18.00 for 18%)', max_digits=5),
        ),
    ]
