# Generated by Django 5.2.16 on 2026-08-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_appsettings_company_gstin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='template_personal_shop_added_to_trunk',
            field=models.CharField(default='personal_shop_added_to_trunk', max_length=100),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='template_personal_shop_executive_assigned',
            field=models.CharField(default='personal_shop_executive_assigned', max_length=100),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='template_personal_shop_needs_info',
            field=models.CharField(default='personal_shop_needs_info', max_length=100),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='template_personal_shop_purchased',
            field=models.CharField(default='personal_shop_purchased', max_length=100),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='template_personal_shop_quotation_ready',
            field=models.CharField(default='personal_shop_quotation_ready', max_length=100),
        ),
    ]
