# Generated by Django 5.2.16 on 2026-08-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_appsettings_template_personal_shop_added_to_trunk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='support_email',
            field=models.EmailField(default='support@cameltrunk.com', help_text='Support email address', max_length=254),
        ),
    ]
