# Generated by Django 5.2.16 on 2026-08-18 06:56

import indiabox.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_encrypt_supabase_service_role_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='supabase_service_role_key',
            field=indiabox.fields.EncryptedCharField(blank=True, help_text='Supabase Service Role Key (for server-side operations) — stored encrypted at rest', max_length=1000),
        ),
    ]
