# Generated by Django 5.2.16 on 2026-08-24 06:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_alter_appsettings_supabase_service_role_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='premium_annual_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('2999.00'), help_text='Annual price (INR) for CamelTrunk Premium self-serve checkout', max_digits=10),
        ),
    ]
