# Generated by Django 5.2.16 on 2026-08-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_appsettings_premium_annual_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='grievance_officer_email',
            field=models.EmailField(blank=True, help_text="Grievance officer's contact email — shown on the Privacy Policy page", max_length=254),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='grievance_officer_name',
            field=models.CharField(blank=True, help_text='Named grievance officer per DPDP Act 2023 — shown on the Privacy Policy page', max_length=150),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='privacy_policy_version',
            field=models.CharField(default='1.0', help_text='Bump this when the Privacy Policy text changes. Snapshotted onto every new ConsentRecord so we know exactly which version a user agreed to.', max_length=20),
        ),
    ]
