# Generated by Django 5.2.16 on 2026-08-27 05:57

import indiabox.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_appsettings_grievance_officer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='razorpay_key_secret',
            field=indiabox.fields.EncryptedCharField(blank=True, help_text='Razorpay Key Secret — stored encrypted at rest', max_length=200),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='razorpay_webhook_secret',
            field=indiabox.fields.EncryptedCharField(blank=True, help_text='Razorpay Webhook Secret — stored encrypted at rest', max_length=200),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='whatsapp_api_token',
            field=indiabox.fields.EncryptedCharField(blank=True, help_text='Permanent Access Token from Meta App Dashboard — stored encrypted at rest', max_length=500),
        ),
    ]
