# Generated by Django 5.2.16 on 2026-08-07 06:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_kycdocument_reviewed_by_locker_is_active_and_more'),
        ('locker', '0006_discardrequest_updated_at_parcel_height_cm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalShopQuotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domestic_shipping_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_gateway_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valid_until', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'TrunkAssist Quotation',
                'verbose_name_plural': 'TrunkAssist Quotations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalShopQuotationLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000)),
                ('variant_details', models.CharField(blank=True, max_length=255)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('unit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='personal_shop.personalshopquotation')),
            ],
            options={
                'verbose_name': 'Quotation Line Item',
                'verbose_name_plural': 'Quotation Line Items',
            },
        ),
        migrations.CreateModel(
            name='PersonalShopRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_id', models.CharField(blank=True, db_index=True, editable=False, max_length=60, null=True, unique=True)),
                ('request_type', models.CharField(choices=[('product_link', 'Product Link'), ('image_search', 'Image Search'), ('cart_screenshot', 'Cart Screenshot'), ('boutique_purchase', 'Boutique Purchase'), ('local_shop_purchase', 'Local Shop Purchase'), ('custom_request', 'Custom Request')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewing', 'Reviewing'), ('executive_assigned', 'Executive Assigned'), ('searching', 'Searching'), ('quotation_ready', 'Quotation Ready'), ('quotation_declined', 'Quotation Declined'), ('quotation_expired', 'Quotation Expired'), ('payment_pending', 'Payment Pending'), ('paid', 'Paid'), ('purchased', 'Purchased'), ('delivered_to_warehouse', 'Delivered to Warehouse'), ('added_to_trunk', 'Added to Trunk'), ('cancelled', 'Cancelled'), ('needs_info', 'Needs Info')], db_index=True, default='submitted', max_length=30)),
                ('destination_country', models.CharField(blank=True, max_length=100)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_url', models.URLField(blank=True, db_index=True, max_length=1000, null=True)),
                ('shop_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('boutique_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('type_details', models.JSONField(blank=True, default=dict)),
                ('refund_required', models.BooleanField(default=False)),
                ('executive_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('searching_started_at', models.DateTimeField(blank=True, null=True)),
                ('quotation_ready_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('added_to_trunk_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='personal_shop.personalshopquotation')),
                ('assigned_executive', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_personal_shop_requests', to=settings.AUTH_USER_MODEL)),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_shop_requests', to='accounts.locker')),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_shop_request', to='locker.parcel')),
            ],
            options={
                'verbose_name': 'TrunkAssist Request',
                'verbose_name_plural': 'TrunkAssist Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='personalshopquotation',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='personal_shop.personalshoprequest'),
        ),
        migrations.CreateModel(
            name='PersonalShopNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_shop_notes', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='personal_shop.personalshoprequest')),
            ],
            options={
                'verbose_name': 'TrunkAssist Note',
                'verbose_name_plural': 'TrunkAssist Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalShopImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_path', models.CharField(blank=True, max_length=500)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='personal_shop.personalshoprequest')),
            ],
            options={
                'verbose_name': 'TrunkAssist Image',
                'verbose_name_plural': 'TrunkAssist Images',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='personalshoprequest',
            index=models.Index(fields=['locker', 'status'], name='idx_pshop_locker_status'),
        ),
        migrations.AddConstraint(
            model_name='personalshopquotation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('request',), name='uniq_pending_quotation_per_request'),
        ),
    ]
