# Generated by Django 5.2.16 on 2026-08-14 06:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalshoprequest',
            options={'ordering': ['-created_at'], 'permissions': [('mark_work_started', 'Can mark TrunkAssist work as started (locks fee as non-refundable)')], 'verbose_name': 'TrunkAssist Request', 'verbose_name_plural': 'TrunkAssist Requests'},
        ),
        migrations.AddField(
            model_name='personalshopquotation',
            name='quotation_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('research_fee', 'Research Fee'), ('expense_advance', 'Expense Advance')], default='purchase', max_length=20),
        ),
        migrations.AddField(
            model_name='personalshopquotation',
            name='travel_expense_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='personalshoprequest',
            name='work_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalshoprequest',
            name='work_started_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who marked work started — audit trail for a non-refundable fee decision.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
