# Generated by Django 5.2.16 on 2026-08-14 10:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_shop', '0002_quotation_type_and_settlement_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalshopquotation',
            name='research_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Only used on Research Fee quotations — auto-suggested when Quotation type is set to Research Fee.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
