# Generated by Django 5.2.16 on 2026-08-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_shop', '0004_personalshoprequest_source_parcel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalshoprequest',
            name='budget_max',
        ),
        migrations.RemoveField(
            model_name='personalshoprequest',
            name='budget_min',
        ),
        migrations.RemoveField(
            model_name='personalshoprequest',
            name='destination_country',
        ),
    ]
