# Generated by Django 5.2.16 on 2026-08-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_shop', '0005_remove_personalshoprequest_budget_max_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalshopquotation',
            options={'ordering': ['-created_at'], 'permissions': [('override_service_fee', 'Can override the auto-suggested TrunkAssist service fee')], 'verbose_name': 'TrunkAssist Quotation', 'verbose_name_plural': 'TrunkAssist Quotations'},
        ),
        migrations.AddField(
            model_name='personalshopquotation',
            name='service_fee_manual_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personalshopquotation',
            name='service_fee_standard_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
