# Generated by Django 5.2.16 on 2026-08-24

from django.db import migrations, models


def backfill_service_fee_standard_amount(apps, schema_editor):
    """0006 added service_fee_standard_amount with default=0 and no backfill.
    Every pre-existing quotation row now has service_fee_standard_amount=0
    while its real service_fee_amount may be nonzero — refresh_service_fee_discount()
    would then "correct" service_fee_amount down to 0 the next time it runs.
    Backfill from the already-charged service_fee_amount for any row still at
    the migration default and with a genuinely nonzero fee, mirroring the
    shipments 0008 shipping_cost_standard/consolidation_fee_standard backfill."""
    PersonalShopQuotation = apps.get_model('personal_shop', 'PersonalShopQuotation')
    PersonalShopQuotation.objects.filter(service_fee_standard_amount=0).exclude(
        service_fee_amount=0
    ).update(service_fee_standard_amount=models.F('service_fee_amount'))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('personal_shop', '0006_alter_personalshopquotation_options_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_service_fee_standard_amount, noop_reverse),
    ]
